# Generated by Django 4.2.2 on 2023-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cpu_temp', models.DecimalField(decimal_places=3, max_digits=4)),
                ('gpu_temp', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
