# Generated by Django 4.2.2 on 2023-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_cpu_cpu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_temp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='fan_speed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='gpu_temp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4),
        ),
    ]
