# Generated by Django 4.2.2 on 2023-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_cpu_cpu_temp_alter_cpu_fan_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cpu_temp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='gpu_temp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
    ]
